//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApIJsonParser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.BoookOrders = new HashSet<BoookOrder>();
            this.NewBooks = new HashSet<NewBook>();
            this.Rates = new HashSet<Rate>();
        }
    
        public int ID { get; set; }
        public string BookName { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> AutoherID { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public string Version { get; set; }
        public string ISBN { get; set; }
        public byte[] CoverImage { get; set; }
        public string CoverImagePath { get; set; }
        public string BookSrc { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual ICollection<BoookOrder> BoookOrders { get; set; }
        public virtual ICollection<NewBook> NewBooks { get; set; }
        public virtual ICollection<Rate> Rates { get; set; }
    }
}
