//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApIJsonParser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public int ID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Comment { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
