//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApIJsonParser
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.BoookOrders = new HashSet<BoookOrder>();
            this.Rates = new HashSet<Rate>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string CriditNumber { get; set; }
        public Nullable<System.DateTime> CriditExpire { get; set; }
        public Nullable<int> PermissionID { get; set; }
    
        public virtual ICollection<BoookOrder> BoookOrders { get; set; }
        public virtual ICollection<Rate> Rates { get; set; }
        public virtual UserPermission UserPermission { get; set; }
    }
}
